version: '2'
services:
  db:
    image: mysql:8.0
    ports:
      - ${LOCAL_MYSQL_PORT}:3306
    volumes:
      - "./docker/.data/db:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    command: --sql_mode=""
  php:
    build:
      context: './docker/php7-fpm'
      args:
        TIMEZONE: ${TIMEZONE}
    volumes:
      - ./:/var/www/symfony
      - ./docker/logs/symfony:/var/www/symfony/var/logs
    environment:
      - SSH_AUTH_SOCK
    ports:
      - ${LOCAL_SOCKETS_PORT}:1414
  nginx:
    build: './docker/nginx'
    ports:
      - ${LOCAL_NGINX_PORT}:80
    volumes_from:
      - php
    volumes:
      - ./docker/logs/nginx/:/var/log/nginx
  elk:
    image: willdurand/elk
    ports:
      - ${LOCAL_LOGSTASH_PORT}:80
    volumes:
      - ./docker/elk/logstash:/etc/logstash
      - ./docker/elk/logstash/patterns:/opt/logstash/patterns
    volumes_from:
      - php
      - nginx
  mailhog:
    image: blueimp/mailhog
    ports:
      - 1025:1025
      - 8025:8025

